package modules

const (
	AzureRKE1            = "azure_rke1"
	AzureRKE2            = "azure_rke2"
	AzureK3s             = "azure_k3s"
	CustomEC2RKE1        = "ec2_rke1_custom"
	CustomEC2RKE2        = "ec2_rke2_custom"
	CustomEC2RKE2Windows = "ec2_rke2_windows_custom"
	CustomEC2K3s         = "ec2_k3s_custom"
	EC2                  = "ec2"
	EC2RKE1              = "ec2_rke1"
	EC2RKE2              = "ec2_rke2"
	EC2K3s               = "ec2_k3s"
	HarvesterRKE1        = "harvester_rke1"
	HarvesterRKE2        = "harvester_rke2"
	HarvesterK3s         = "harvester_k3s"
	ImportEC2RKE1        = "ec2_rke1_import"
	ImportEC2RKE2        = "ec2_rke2_import"
	ImportEC2K3s         = "ec2_k3s_import"
	LinodeRKE1           = "linode_rke1"
	LinodeRKE2           = "linode_rke2"
	LinodeK3s            = "linode_k3s"
	VsphereRKE1          = "vsphere_rke1"
	VsphereRKE2          = "vsphere_rke2"
	VsphereK3s           = "vsphere_k3s"
	AirgapRKE1           = "airgap_rke1"
	AirgapRKE2           = "airgap_rke2"
	AirgapK3S            = "airgap_k3s"
)
