---
name: "Set Rancher Repo"
description: "Sets the Rancher repo to 'latest' for RC versions, 'alpha' for alpha versions, or falls back to a specified repo"
inputs:
  rancher-version:
    description: "The rancher version to check for RC or alpha"
    required: true
  fallback-repo:
    description: "The fallback repo to use if no RC/alpha detected"
    default: ""
  is-prime:
    description: "Determines if the Rancher is Prime or Community"
    default: false
  release-prime-version:
    description: "The release prime version to use when is-prime is true"
    default: ""
  env-var-name:
    description: "The name of the environment variable to set"
    default: "RANCHER_REPO"
outputs:
  repo:
    description: "The determined repo"
    value: ${{ steps.determine-repo.outputs.repo }}
runs:
  using: "composite"
  steps:
    - name: Determine repo
      id: determine-repo
      shell: bash
      run: |
        RANCHER_VERSION="${{ inputs.rancher-version }}"
        FALLBACK_REPO="${{ inputs.fallback-repo }}"
        IS_PRIME="${{ inputs.is-prime }}"
        RELEASE_PRIME_VERSION="${{ inputs.release-prime-version }}"

        if [[ "$RANCHER_VERSION" == *"-rc"* ]]; then
          REPO="latest"
        elif [[ "$RANCHER_VERSION" == *"-alpha"* ]]; then
          REPO="alpha"
        elif [[ "$IS_PRIME" == "true" && -z "$RELEASE_PRIME_VERSION" ]]; then
          REPO="prime"
        elif [[ "$IS_PRIME" == "true" && -n "$RELEASE_PRIME_VERSION" ]]; then
          REPO="release-$RELEASE_PRIME_VERSION"
        else
          REPO="$FALLBACK_REPO"
        fi
        
        echo "repo=$REPO" >> $GITHUB_OUTPUT
    
    - name: Set environment variable
      uses: ./.github/actions/set-env-var
      with:
        key: ${{ inputs.env-var-name }}
        value: ${{ steps.determine-repo.outputs.repo }}
