---
name: "GCP Provider Setup"
description: "Sets up the specified cloud provider environment"
inputs:
  downstream-cluster-provider:
    description: "Cloud provider for downstream cluster"
    required: true
  iam-role:
    description: "IAM Role to assume for AWS"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  region:
    description: "AWS Region"
    required: true
  gcp-service-account:
    description: "Google Cloud Service Account JSON"
    required: true

runs:
  using: composite
  steps:
    - if: ${{ inputs.downstream-cluster-provider == 'aws' }}
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
      with:
        role-to-assume: ${{ inputs.iam-role }}
        aws-region: ${{ inputs.region }}

    - if: ${{ inputs.downstream-cluster-provider == 'aws' }}
      name: Get AWS credentials from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa #v3
      with:
        secret-ids: |
          AWS_ACCESS_KEY, ${{ inputs.aws-access-key-id }}
          AWS_SECRET_KEY, ${{ inputs.aws-secret-access-key }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
      with:
        credentials_json: ${{ inputs.gcp-service-account }}
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db #v3