---
name: "Whitelist Runner IP"
description: "Add runner IP to AWS prefix list"
inputs:
  cloud-provider:
    description: "Cloud provider to use"
    required: true
  prefix-list-id:
    description: "AWS prefix list ID"
    required: true
  aws-region:
    description: "AWS region"
    required: true

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.cloud-provider == 'aws' }}
      name: Refresh AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.iam-role }}
        aws-region: ${{ inputs.aws-region }}

    - if: ${{ inputs.cloud-provider == 'aws' }}
      name: AWS whitelist IP
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/aws-whitelist.sh"
        PREFIX_LIST_ID="${{ inputs.prefix-list-id }}" \
        REGION="${{ inputs.aws-region }}" \
        "${{ github.action_path }}/aws-whitelist.sh"