---
name: "AWS Provider Setup"
description: "Sets up the AWS cloud provider environment"
inputs:
  iam-role:
    description: "IAM Role to assume for AWS"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  region:
    description: "AWS Region"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.iam-role }}
        aws-region: ${{ inputs.region }}

    - name: Get AWS credentials from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          AWS_ACCESS_KEY, ${{ inputs.aws-access-key-id }}
          AWS_SECRET_KEY, ${{ inputs.aws-secret-access-key }}