package clusters

const (
	CloudCredentialID = "cloud_credential_id"

	MachineConfig         = "machine_config"
	MachineGlobalConfig   = "machine_global_config"
	MachineSelectorConfig = "machine_selector_config"
	MachinePools          = "machine_pools"
	NodePool              = "node-pool"
	Etcd                  = "etcd"
	Enabled               = "enabled"
	RancherClusterID      = "cluster_id"
	Quantity              = "quantity"
	ChartValues           = "chart_values"

	AgentEnvVars                        = "agent_env_vars"
	RkeConfig                           = "rke_config"
	Networking                          = "networking"
	StackPreference                     = "stack_preference"
	KubernetesVersion                   = "kubernetes_version"
	Network                             = "network"
	Plugin                              = "plugin"
	RKE1PrivateRegistries               = "private_registries"
	PrivateRegistries                   = "registries"
	EngineInsecureRegistry              = "engine_insecure_registry"
	Config                              = "config"
	Configs                             = "configs"
	Mirrors                             = "mirrors"
	Services                            = "services"
	EnableNetworkPolicy                 = "enable_network_policy"
	DefaultClusterRoleForProjectMembers = "default_cluster_role_for_project_members"
	RancherBaseline                     = "rancher-baseline"

	DataDirectories = "data_directories"
	SystemAgent     = "system_agent"
	Provisioning    = "provisioning"
	K8sDistro       = "k8s_distro"

	Locals                          = "locals"
	ResourcePrefix                  = "resource_prefix"
	RoleFlags                       = "role_flags"
	AllFlags                        = "--etcd --controlplane --worker"
	EtcdRoleFlag                    = "--etcd"
	ControlPlaneRoleFlag            = "--controlplane"
	WorkerRoleFlag                  = "--worker"
	NodeNameFlag                    = "--node-name"
	OriginalNodeCommand             = "original_node_command"
	WindowsOriginalNodeCommand      = "windows_original_node_command"
	WindowsProxyOriginalNodeCommand = "windows_proxy_original_node_command"
	InsecureCommand                 = "insecure_command"
	InsecureNodeCommand             = "insecure_node_command"
	InsecureWindowsNodeCommand      = "insecure_windows_node_command"
	InsecureWindowsProxyNodeCommand = "insecure_windows_proxy_node_command"
	ClusterRegistrationToken        = "cluster_registration_token"
	NodeCommand                     = "node_command"
	WindowsNodeCommand              = "windows_node_command"
)
