package general

const (
	KubernetesSource  = "hashicorp/kubernetes"
	Insecure          = "insecure"
	LocalSource       = "hashicorp/local"
	Provider          = "provider"
	Rancher2          = "rancher2"
	RC                = "-rc"
	RequiredProviders = "required_providers"
	AdminUser         = "admin_user"
	Source            = "source"
	Terraform         = "terraform"
	TokenKey          = "token_key"
	Version           = "version"

	ApiUrl      = "api_url"
	Destination = "destination"
	Helm        = "helm"
	Local       = "local"
	Locals      = "locals"
	Kubernetes  = "kubernetes"

	Data         = "data"
	Description  = "description"
	Label        = "label"
	Port         = "port"
	Resource     = "resource"
	ResourceKind = "kind"
	ResourceName = "name"
	Namespace    = "namespace"
	Triggers     = "triggers"
	Value        = "value"

	DependsOn    = "depends_on"
	GenerateName = "generate_name"
	Defaults     = "defaults"
	Index        = "index"
	File         = "file"
	Airgap       = "airgap"
	Custom       = "custom"
	Import       = "import"
	Registry     = "registry"

	Count   = "count"
	LogFile = "log_file"
	Tags    = "tags"
	Timeout = "timeout"
	Token   = "token"
	Type    = "type"

	ConfigPath       = "config_path"
	Connection       = "connection"
	Host             = "host"
	Inline           = "inline"
	TargetPlatform   = "target_platform"
	NullResource     = "null_resource"
	RandomPassword   = "random_password"
	TimeSleep        = "time_sleep"
	CreateDuration   = "create_duration"
	RegisterNodes    = "register_nodes"
	PrivateKey       = "private_key"
	Provisioner      = "provisioner"
	RemoteExec       = "remote-exec"
	Ssh              = "ssh"
	WinRM            = "winrm"
	UseNTLM          = "use_ntlm"
	User             = "user"
	Password         = "password"
	UserData         = "user_data"
	Self             = "self"
	Windows          = "windows"
	PublicIp         = "public_ip"
	IPV6Addresses    = "ipv6_addresses"
	PrivateIp        = "private_ip"
	DefaultIPAddress = "default_ip_address"
	IPAddress        = "ip_address"
	PrivateIPAddress = "private_ip_address"
	Length           = "length"
	Min              = "min"
	Max              = "max"
)
