---
name: "AWS Resource Cleanup"
description: "Delete AWS resources that begin with a given prefix"

inputs:
  prefix:
    description: "Resource prefix to target and delete"
    required: true
  region:
    description: "AWS region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Custodian cleanup
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/cleanup.sh"
        PREFIX="${{ inputs.prefix }}" \
        AWS_REGION="${{ inputs.region }}" \
        "${{ github.action_path }}/cleanup.sh"
