---
name: Run Rancher2 Test Suite
description: "Runs rancher2 test suite"
inputs:
  suite:
    description: "The specific Rancher2 suite to run on the specific Rancher server"
    required: false
  package:
    description: "Package to test"
    required: true
  test-suite:
    description: "Suite to test"
    required: true
  timeout:
    description: "Timeout"
    required: true
runs:
  using: composite
  steps:
    - name: Run Tests
      id: tests
      run: |
        set +e
        case "${{ inputs.suite }}" in
          rancher-server-one)
            gotestsum --format standard-verbose --packages=github.com/rancher/tfp-automation/tests/${{ inputs.package }}/provisioning \
            --junitfile results.xml --jsonfile results_provision.json -- -timeout=${{ inputs.timeout }} -tags=recurring -v;
            provision_code=$?;
            echo "provision_code=$provision_code" >> $GITHUB_ENV;
            cp results_provision.json results.json
            ./pipeline/scripts/build_qase_reporter.sh;
            ./reporter;

            gotestsum --format standard-verbose --packages=github.com/rancher/tfp-automation/tests/${{ inputs.package }}/psact \
            --junitfile results.xml --jsonfile results_psact.json -- -timeout=${{ inputs.timeout }} -tags=recurring -v;
            psact_code=$?;
            echo "psact_code=$psact_code" >> $GITHUB_ENV;
            cp results_psact.json results.json
            ./pipeline/scripts/build_qase_reporter.sh;
            ./reporter;
            ;;
          rancher-server-two)
            gotestsum --format standard-verbose --packages=github.com/rancher/tfp-automation/tests/${{ inputs.package }}/rbac \
            --junitfile results.xml --jsonfile results_rbac.json -- -timeout=${{ inputs.timeout }} -tags=recurring -v;
            rbac_code=$?;
            echo "rbac_code=$rbac_code" >> $GITHUB_ENV;
            cp results_rbac.json results.json
            ./pipeline/scripts/build_qase_reporter.sh;
            ./reporter;
              
            gotestsum --format standard-verbose --packages=github.com/rancher/tfp-automation/tests/${{ inputs.package }}/snapshot \
            --junitfile results.xml --jsonfile results_snapshot.json -- -timeout=${{ inputs.timeout }} -tags=recurring -v;
            snapshot_code=$?;
            echo "snapshot_code=$snapshot_code" >> $GITHUB_ENV;
            cp results_snapshot.json results.json
            ./pipeline/scripts/build_qase_reporter.sh;
            ./reporter;
            ;;
        esac
      shell: bash
      continue-on-error: true

    - name: Show failed tests
      run: |
         declare -A suites=(
           [provision_code]="Provisioning:results_provision.json"
           [psact_code]="PSACT:results_psact.json"
           [rbac_code]="RBAC:results_rbac.json"
           [snapshot_code]="Snapshot:results_snapshot.json"
         )

         failed=0
         for exit_code in "${!suites[@]}"; do
          IFS=: read suite_name results_file <<< "${suites[$exit_code]}"
          exit_val="${!exit_code}"

          if [ "$exit_val" != "" ] && [ "$exit_val" -ne 0 ]; then
            echo "Failed $suite_name tests:"
            jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' "$results_file"
            failed=1
          fi
         done

         if [ "$failed" -eq 1 ]; then
          exit 1
         fi
      shell: bash