package azure

const (
	AzureCredentialConfig = "azure_credential_config"
	ClientID              = "client_id"
	ClientSecret          = "client_secret"
	Environment           = "environment"
	SubscriptionID        = "subscription_id"
	TenantID              = "tenant_id"

	AKSConfig   = "aks_config_v2"
	AzureConfig = "azure_config"
	NodePools   = "node_pools"

	OutboundType            = "outbound_type"
	ResourceGroup           = "resource_group"
	ResourceLocation        = "resource_location"
	DNSPrefix               = "dns_prefix"
	NetworkPlugin           = "network_plugin"
	VirtualNetwork          = "virtual_network"
	Subnet                  = "subnet"
	NetworkDNSServiceIP     = "network_dns_service_ip"
	NetworkDockerBridgeCIDR = "network_docker_bridge_cidr"
	NetworkServiceCIDR      = "network_service_cidr"

	AvailabilitySet   = "availability_set"
	CustomData        = "custom_data"
	DiskSize          = "disk_size"
	FaultDomainCount  = "fault_domain_count"
	Image             = "image"
	Location          = "location"
	ManagedDisks      = "managed_disks"
	NoPublicIP        = "no_public_ip"
	OpenPort          = "open_port"
	PrivateIPAddress  = "private_ip_address"
	Size              = "size"
	SSHUser           = "ssh_user"
	StaticPublicIP    = "static_public_ip"
	StorageType       = "storage_type"
	UpdateDomainCount = "update_domain_count"
	UsePrivateIP      = "use_private_ip"

	AvailabilityZones   = "availability_zones"
	Count               = "count"
	NodePoolMode        = "mode"
	OrchestratorVersion = "orchestrator_version"
	OSDiskSizeGB        = "os_disk_size_gb"
	Taints              = "taints"
	VMSize              = "vm_size"
)
