---
name: Compare Rancher tag
description: "Compares the latest Rancher tag for specified release lines with cached values"
inputs:
  cached-tag-v214:
    required: true
  cached-tag-v213:
    required: true
  cached-tag-v212:
    required: true
  latest-tag-v214:
    required: true
  latest-tag-v213:
    required: true
  latest-tag-v212:
    required: true
outputs:
  is_tag_new_v214:
    value: ${{ steps.compare.outputs.is_tag_new_v214 }}
  is_tag_new_v213:
    value: ${{ steps.compare.outputs.is_tag_new_v213 }}
  is_tag_new_v212:
    value: ${{ steps.compare.outputs.is_tag_new_v212 }}
runs:
  using: composite
  steps:
    - id: compare
      run: |
        for RELEASE_LINE in v214 v213 v212; do
          if [[ "$RELEASE_LINE" = "v214" ]]; then
            TAG_INPUT="${{ inputs.latest-tag-v214 }}"
            CACHED_TAG="${{ inputs.cached-tag-v214 }}"
          elif [[ "$RELEASE_LINE" = "v213" ]]; then
            TAG_INPUT="${{ inputs.latest-tag-v213 }}"
            CACHED_TAG="${{ inputs.cached-tag-v213 }}"
          elif [[ "$RELEASE_LINE" = "v212" ]]; then
            TAG_INPUT="${{ inputs.latest-tag-v212 }}"
            CACHED_TAG="${{ inputs.cached-tag-v212 }}"
          fi

          echo "Cached Rancher tag for $RELEASE_LINE: $CACHED_TAG"
          echo "Latest Rancher tag for $RELEASE_LINE: $TAG_INPUT"

          if [ "$CACHED_TAG" != "$TAG_INPUT" ]; then
            echo "New tag for $RELEASE_LINE: $TAG_INPUT"
            eval "IS_TAG_NEW_$RELEASE_LINE=true"
          else
            echo "No new tag found yet for $RELEASE_LINE..."
            eval "IS_TAG_NEW_$RELEASE_LINE=false"
          fi
        done

        echo "is_tag_new_v214=$IS_TAG_NEW_v214" >> $GITHUB_OUTPUT
        echo "is_tag_new_v213=$IS_TAG_NEW_v213" >> $GITHUB_OUTPUT
        echo "is_tag_new_v212=$IS_TAG_NEW_v212" >> $GITHUB_OUTPUT
      shell: bash