---
name: Get latest Rancher tag
description: Gets the latest Rancher tag for the specified release lines
inputs:
  release_lines:
    description: "List Rancher release lines"
    required: true
  prime_artifacts_path:
    description: "Path to prime artifacts"
    required: true
outputs:
  latest_tag_v215:
    description: "Latest tag for v2.15"
    value: ${{ steps.set-outputs.outputs.latest_tag_v215 }}
  latest_tag_v214:
    description: "Latest tag for v2.14"
    value: ${{ steps.set-outputs.outputs.latest_tag_v214 }}
  latest_tag_v213:
    description: "Latest tag for v2.13"
    value: ${{ steps.set-outputs.outputs.latest_tag_v213 }}
  previous_tag_v215:
    description: "Previous tag for v2.15"
    value: ${{ steps.set-outputs.outputs.previous_tag_v215 }}
  previous_tag_v214:
    description: "Previous tag for v2.14"
    value: ${{ steps.set-outputs.outputs.previous_tag_v214 }}
  previous_tag_v213:
    description: "Previous tag for v2.13"
    value: ${{ steps.set-outputs.outputs.previous_tag_v213 }}
runs:
  using: composite
  steps:
    - id: get-tags
      run: |
        RELEASE_LINES="${{ inputs.release_lines }}"
        TAGS=$(curl -s https://api.github.com/repos/rancher/rancher/releases | jq -r '.[].tag_name')

        for RELEASE_LINE in $RELEASE_LINES; do
          TAG_LIST=$(curl -s https://api.github.com/repos/rancher/rancher/releases | jq -r '.[].tag_name' | grep -E "^$RELEASE_LINE" | sort -V -r)
          LATEST_VERSION=$(echo "$TAG_LIST" | head -n 1)
          PREVIOUS_VERSION=$(echo "$TAG_LIST" | sed -n '2p')

          SUFFIX=$(echo "$RELEASE_LINE" | tr -d '.')

          if [[ -z "$LATEST_VERSION" ]]; then
            echo "No tag found for $RELEASE_LINE, skipping..."
            eval "LATEST_TAG_${SUFFIX}=''"
            eval "PREVIOUS_TAG_${SUFFIX}=''"
            echo "LATEST_TAG_${SUFFIX}=" >> $GITHUB_ENV
            echo "PREVIOUS_TAG_${SUFFIX}=" >> $GITHUB_ENV
            continue
          fi

          echo "Latest tag for $RELEASE_LINE: $LATEST_VERSION"
          echo "Previous tag for $RELEASE_LINE: $PREVIOUS_VERSION"

          if [[ "$RELEASE_LINE" == "v2.14" || "$RELEASE_LINE" == "v2.15" ]]; then
            RELEASE_JSON=$(curl -s "https://api.github.com/repos/rancher/rancher/releases/tags/$LATEST_VERSION")
            ASSET_COUNT=$(echo "$RELEASE_JSON" | jq '.assets | length')

            echo "Asset count for $LATEST_VERSION: $ASSET_COUNT"

            if [ "$ASSET_COUNT" -lt 17 ]; then
              echo "Asset count: $ASSET_COUNT. Expected at least 17 assets..."
              LATEST_VERSION=""
            else
              echo "Checking for Prime artifacts for $LATEST_VERSION..."
              curl -sf ${{ inputs.prime_artifacts_path }}/$LATEST_VERSION/rancher-images.txt > /dev/null
              if [[ $? -ne 0 ]]; then
                echo "Unable to reach: ${{ inputs.prime_artifacts_path }}/$LATEST_VERSION/rancher-images.txt"
                LATEST_VERSION=""
              fi
            fi
          else
            RELEASE_JSON=$(curl -s ${{ inputs.prime_artifacts_path }}/$RELEASE_LINE/rancher-images.txt)

            if [[ $? -ne 0 ]]; then
              echo "Unable to reach: ${{ inputs.prime_artifacts_path }}/$RELEASE_LINE/rancher-images.txt"
              LATEST_VERSION=""
            fi
          fi

          eval "LATEST_TAG_${SUFFIX}=$LATEST_VERSION"
          eval "PREVIOUS_TAG_${SUFFIX}=$PREVIOUS_VERSION"
          echo "LATEST_TAG_${SUFFIX}=$LATEST_VERSION" >> $GITHUB_ENV
          echo "PREVIOUS_TAG_${SUFFIX}=$PREVIOUS_VERSION" >> $GITHUB_ENV
        done
      shell: bash
    - id: set-outputs
      run: |
        echo "latest_tag_v215=${LATEST_TAG_v215}" >> $GITHUB_OUTPUT
        echo "latest_tag_v214=${LATEST_TAG_v214}" >> $GITHUB_OUTPUT
        echo "latest_tag_v213=${LATEST_TAG_v213}" >> $GITHUB_OUTPUT
        echo "previous_tag_v215=${PREVIOUS_TAG_v215}" >> $GITHUB_OUTPUT
        echo "previous_tag_v214=${PREVIOUS_TAG_v214}" >> $GITHUB_OUTPUT
        echo "previous_tag_v213=${PREVIOUS_TAG_v213}" >> $GITHUB_OUTPUT
      shell: bash