---
name: Check Rancher Tag

on:
  schedule:
    - cron: "0 16,20 * * 1-5"
    - cron: "0 0 * * 2-6"
  workflow_dispatch:
    inputs:
      override:
        description: "Run all tests for the selected alpha, even if some have already passed"
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  get-dispatch-workflow-list:
    runs-on: ubuntu-latest
    outputs:
      workflow_list: ${{ steps.get-list.outputs.workflow_list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Get workflow list from dispatch-workflows.yaml
        id: get-list
        uses: ./.github/actions/get-dispatch-workflow-list

  check-latest-rancher-tag:
    # if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
    needs: get-dispatch-workflow-list
    runs-on: ubuntu-latest
    env:
      RANCHER_RELEASE_LINES: "v2.15 v2.14 v2.13"
      SANITIZED_RELEASES: "v215 v214 v213"
    outputs:
      latest_tag_V215: ${{ steps.get-latest-tag.outputs.latest_tag_v215 }}
      latest_tag_v214: ${{ steps.get-latest-tag.outputs.latest_tag_v214 }}
      latest_tag_v213: ${{ steps.get-latest-tag.outputs.latest_tag_v213 }}
      previous_tag_v215: ${{ steps.get-latest-tag.outputs.previous_tag_v215 }}
      previous_tag_v214: ${{ steps.get-latest-tag.outputs.previous_tag_v214 }}
      previous_tag_v213: ${{ steps.get-latest-tag.outputs.previous_tag_v213 }}
      is_tag_new_v215: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v215 }}
      is_tag_new_v214: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v214 }}
      is_tag_new_v213: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v213 }}
      dispatch_workflow_list: ${{ needs.get-dispatch-workflow-list.outputs.workflow_list }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get dispatch workflow list
        id: get-dispatch-workflow-list
        uses: ./.github/actions/get-dispatch-workflow-list

      - name: Fetch Rancher tags from S3
        run: |
          for release in $SANITIZED_RELEASES; do
            if aws s3 ls "s3://${{ secrets.RANCHER_TAG_BUCKET }}/tag_${release}.txt" > /dev/null 2>&1; then
              aws s3 cp "s3://${{ secrets.RANCHER_TAG_BUCKET }}/tag_${release}.txt" "tag/tag_${release}.txt"
            else
              echo "Skipping $release — no tag file found in bucket."
            fi
          done

      - name: Get latest Rancher tag
        id: get-latest-tag
        uses: ./.github/actions/get-latest-rancher-tag
        with:
          release_lines: ${{ env.RANCHER_RELEASE_LINES }}
          prime_artifacts_path: ${{ secrets.PRIME_ARTIFACTS_PATH }}

      - name: Read cached Rancher tags
        id: read-cached-tags
        run: |
          for release in $SANITIZED_RELEASES; do
            cache_tag="CACHED_TAG_${release}"
            file="tag/tag_${release}.txt"
            version=$(cat "$file" 2>/dev/null || echo '')
            echo "${cache_tag}=${version}" >> $GITHUB_ENV
          done

      - name: Compare latest Rancher tag against cached tag
        id: compare-rancher-tag
        uses: ./.github/actions/compare-rancher-tag
        with:
          cached-tag-v215: ${{ env.CACHED_TAG_v215 }}
          cached-tag-v214: ${{ env.CACHED_TAG_v214 }}
          cached-tag-v213: ${{ env.CACHED_TAG_v213 }}
          latest-tag-v215: ${{ steps.get-latest-tag.outputs.latest_tag_v215 }}
          latest-tag-v214: ${{ steps.get-latest-tag.outputs.latest_tag_v214 }}
          latest-tag-v213: ${{ steps.get-latest-tag.outputs.latest_tag_v213 }}

      - name: Write latest tags to files
        env:
          LATEST_TAG_V215: ${{ steps.get-latest-tag.outputs.latest_tag_v215 }}
          LATEST_TAG_V214: ${{ steps.get-latest-tag.outputs.latest_tag_v214 }}
          LATEST_TAG_V213: ${{ steps.get-latest-tag.outputs.latest_tag_v213 }}
        run: |
          mkdir -p tag
          for release in $SANITIZED_RELEASES; do
            latest_tag="LATEST_TAG_${release^^}"
            echo "${!latest_tag}" > tag/tag_${release}.txt
          done

      - name: Update Rancher tags to S3
        run: |
          for release in $SANITIZED_RELEASES; do
            aws s3 cp "tag/tag_${release}.txt" "s3://${{ secrets.RANCHER_TAG_BUCKET }}/tag_${release}.txt"
          done

  set-latest-chart-version:
    needs: check-latest-rancher-tag
    runs-on: ubuntu-latest
    outputs:
      chart_version_v215: ${{ steps.set-latest-chart-version.outputs.chart_version_v215 }}
      chart_version_v214: ${{ steps.set-latest-chart-version.outputs.chart_version_v214 }}
      chart_version_v213: ${{ steps.set-latest-chart-version.outputs.chart_version_v213 }}

    steps:
      - name: Chart versions
        id: set-latest-chart-version
        run: |
          CHART_V215="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v215 }}"
          CHART_V214="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v214 }}"
          CHART_V213="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v213 }}"

          echo "chart_version_v215=${CHART_V215#v}" >> $GITHUB_OUTPUT
          echo "chart_version_v214=${CHART_V214#v}" >> $GITHUB_OUTPUT
          echo "chart_version_v213=${CHART_V213#v}" >> $GITHUB_OUTPUT

  check-individual-tests-v215:
    needs: [check-latest-rancher-tag, set-latest-chart-version, get-dispatch-workflow-list]
    runs-on: ubuntu-latest
    outputs:
      failed_workflows_v215: ${{ steps.check.outputs.failed_workflows_v215 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Check test results for v2.15
        id: check
        uses: ./.github/actions/check-rancher-tag-result
        with:
          rancher_tag: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v215 }}
          previous_rancher_tag: ${{ needs.check-latest-rancher-tag.outputs.previous_tag_v215 }}
          dispatch_workflow_list: ${{ needs.get-dispatch-workflow-list.outputs.workflow_list }}
          github_token: ${{ github.token }}
  
  check-individual-tests-v214:
    needs: [check-latest-rancher-tag, set-latest-chart-version, get-dispatch-workflow-list]
    runs-on: ubuntu-latest
    outputs:
      failed_workflows_v214: ${{ steps.check.outputs.failed_workflows_v214 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Check test results for v2.14
        id: check
        uses: ./.github/actions/check-rancher-tag-result
        with:
          rancher_tag: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v214 }}
          previous_rancher_tag: ${{ needs.check-latest-rancher-tag.outputs.previous_tag_v214 }}
          dispatch_workflow_list: ${{ needs.get-dispatch-workflow-list.outputs.workflow_list }}
          github_token: ${{ github.token }}

  check-individual-tests-v213:
    needs: [check-latest-rancher-tag, set-latest-chart-version, get-dispatch-workflow-list]
    runs-on: ubuntu-latest
    outputs:
      failed_workflows_v213: ${{ steps.check.outputs.failed_workflows_v213 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Check test results for v2.13
        id: check
        uses: ./.github/actions/check-rancher-tag-result
        with:
          rancher_tag: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v213 }}
          previous_rancher_tag: ${{ needs.check-latest-rancher-tag.outputs.previous_tag_v213 }}
          dispatch_workflow_list: ${{ needs.get-dispatch-workflow-list.outputs.workflow_list }}
          github_token: ${{ github.token }}
  
  trigger-tests-v215:
    needs: [check-latest-rancher-tag, set-latest-chart-version, check-individual-tests-v215, get-dispatch-workflow-list]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v215 == 'true' && (needs.check-individual-tests-v215.outputs.failed_workflows_v215 != '' || github.event.inputs.override == 'true') }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v215 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v215 }}
      workflow_list: ${{ (github.event.inputs.override == 'true' && needs.get-dispatch-workflow-list.outputs.workflow_list) || needs.check-individual-tests-v215.outputs.failed_workflows_v215 }}
  
  trigger-tests-v214:
    needs: [check-latest-rancher-tag, set-latest-chart-version, check-individual-tests-v214, get-dispatch-workflow-list]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v214 == 'true' && (needs.check-individual-tests-v214.outputs.failed_workflows_v214 != '' || github.event.inputs.override == 'true') }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v214 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v214 }}
      workflow_list: ${{ (github.event.inputs.override == 'true' && needs.get-dispatch-workflow-list.outputs.workflow_list) || needs.check-individual-tests-v214.outputs.failed_workflows_v214 }}

  trigger-tests-v213:
    needs: [check-latest-rancher-tag, set-latest-chart-version, check-individual-tests-v213, get-dispatch-workflow-list]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v213 == 'true' && (needs.check-individual-tests-v213.outputs.failed_workflows_v213 != '' || github.event.inputs.override == 'true') }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v213 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v213 }}
      workflow_list: ${{ (github.event.inputs.override == 'true' && needs.get-dispatch-workflow-list.outputs.workflow_list) || needs.check-individual-tests-v213.outputs.failed_workflows_v213 }}

  notify-slack-v215:
    needs: [check-individual-tests-v215, check-latest-rancher-tag]
    runs-on: ubuntu-latest
    if: ${{ needs.check-individual-tests-v215.outputs.failed_workflows_v215 == '' && needs.check-latest-rancher-tag.outputs.latest_tag_v215 != '' }}
    steps:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
         with:
           role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
           aws-region: ${{ secrets.AWS_REGION }}

       - name: Check if Slack notification already sent
         id: check_marker
         run: |
          TAG="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v215 }}"
          BASE_TAG=$(echo "$TAG" | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+')
          MARKER_FILE="slack_notified_${BASE_TAG}.txt"

          echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV

          if aws s3 ls "s3://${{ secrets.RANCHER_TAG_BUCKET }}/$MARKER_FILE" > /dev/null 2>&1; then
            echo "Notification already sent for $BASE_TAG. Skipping."
            echo "skip_slack=true" >> $GITHUB_OUTPUT
          else
            echo "skip_slack=false" >> $GITHUB_OUTPUT
          fi
      
       - name: Send Slack notification for v2.15
         if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
         uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 #v3
         with:
          webhook: ${{ secrets.TEAM_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "*[rancher/tfp-automation]* :alert:\n`${{ env.BASE_TAG }}` Release Testing Completed :white_check_mark:"
            }
      
       - name: Configure AWS credentials
         if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
         uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
         with:
           role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
           aws-region: ${{ secrets.AWS_REGION }}

       - name: Write Slack notification marker to S3
         if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
         run: |
          MARKER_FILE="slack_notified_${BASE_TAG}.txt"
          echo "notified" > $MARKER_FILE
          aws s3 cp "$MARKER_FILE" "s3://${{ secrets.RANCHER_TAG_BUCKET }}/$MARKER_FILE"
  
  notify-slack-v214:
    needs: [check-individual-tests-v214, check-latest-rancher-tag]
    runs-on: ubuntu-latest
    if: ${{ needs.check-individual-tests-v214.outputs.failed_workflows_v214 == '' && needs.check-latest-rancher-tag.outputs.latest_tag_v214 != '' }}
    steps:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
         with:
           role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
           aws-region: ${{ secrets.AWS_REGION }}

       - name: Check if Slack notification already sent
         id: check_marker
         run: |
          TAG="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v214 }}"
          BASE_TAG=$(echo "$TAG" | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+')
          MARKER_FILE="slack_notified_${BASE_TAG}.txt"

          echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV

          if aws s3 ls "s3://${{ secrets.RANCHER_TAG_BUCKET }}/$MARKER_FILE" > /dev/null 2>&1; then
            echo "Notification already sent for $BASE_TAG. Skipping."
            echo "skip_slack=true" >> $GITHUB_OUTPUT
          else
            echo "skip_slack=false" >> $GITHUB_OUTPUT
          fi
      
       - name: Send Slack notification for v2.14
         if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
         uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 #v3
         with:
          webhook: ${{ secrets.TEAM_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "*[rancher/tfp-automation]* :alert:\n`${{ env.BASE_TAG }}` Release Testing Completed :white_check_mark:"
            }
      
       - name: Configure AWS credentials
         if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
         uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
         with:
           role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
           aws-region: ${{ secrets.AWS_REGION }}

       - name: Write Slack notification marker to S3
         if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
         run: |
          MARKER_FILE="slack_notified_${BASE_TAG}.txt"
          echo "notified" > $MARKER_FILE
          aws s3 cp "$MARKER_FILE" "s3://${{ secrets.RANCHER_TAG_BUCKET }}/$MARKER_FILE"

  notify-slack-v213:
    needs: [check-individual-tests-v213, check-latest-rancher-tag]
    runs-on: ubuntu-latest
    if: ${{ needs.check-individual-tests-v213.outputs.failed_workflows_v213 == '' && needs.check-latest-rancher-tag.outputs.latest_tag_v213 != '' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check if Slack notification already sent
        id: check_marker
        run: |
          TAG="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v213 }}"
          BASE_TAG=$(echo "$TAG" | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+')
          MARKER_FILE="slack_notified_${BASE_TAG}.txt"

          echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV

          if aws s3 ls "s3://${{ secrets.RANCHER_TAG_BUCKET }}/$MARKER_FILE" > /dev/null 2>&1; then
            echo "Notification already sent for $BASE_TAG. Skipping."
            echo "skip_slack=true" >> $GITHUB_OUTPUT
          else
            echo "skip_slack=false" >> $GITHUB_OUTPUT
          fi
    
      - name: Send Slack notification for v2.13
        if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 #v3
        with:
          webhook: ${{ secrets.TEAM_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "*[rancher/tfp-automation]* :alert:\n`${{ env.BASE_TAG }}` Release Testing Completed :white_check_mark:"
            }
    
      - name: Configure AWS credentials
        if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Write Slack notification marker to S3
        if: ${{ steps.check_marker.outputs.skip_slack == 'false' }}
        run: |
          MARKER_FILE="slack_notified_${BASE_TAG}.txt"
          echo "notified" > $MARKER_FILE
          aws s3 cp "$MARKER_FILE" "s3://${{ secrets.RANCHER_TAG_BUCKET }}/$MARKER_FILE"