name: Dispatch Workflows

on:
  workflow_call:
    inputs:
      rancher_version:
        required: true
        type: string
      rancher_chart_version:
        required: true
        type: string
      workflow_list:
        required: true
        type: string

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          workflows_json=$(printf '%s\n' "${{ inputs.workflow_list }}" | jq -Rc 'split(",")')
          echo "matrix=$workflows_json" >> $GITHUB_OUTPUT

  run-tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workflow: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}

    steps:
      - name: Trigger test workflow ${{ matrix.workflow }}
        run: |
          echo "Dispatching: ${{ matrix.workflow }}"

          curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ matrix.workflow }}/dispatches \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" -d '{"ref": "main","inputs": {"rancher_version": "${{ inputs.rancher_version }}","rancher_chart_version": "${{ inputs.rancher_chart_version }}"}}'