---
name: Qase Test Upload
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/schemas/**'
  
jobs:
  update-qase:
    name: update-qase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: recursive
      
      - name: Set up Go environment
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: "./go.mod"

      - name: Update Qase
        env:
          QASE_AUTOMATION_TOKEN: ${{ secrets.QASE_TOKEN }}
        run: go run ./pipeline/qase/schemaupload/main.go