---
name: Verify Changes

on:
  pull_request:
    branches:
      - main

jobs:
  verify-changes:
    name: golang-ci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: "./go.mod"

      - name: Go Version
        run: go version

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/

      - name: Verify Go Mod
        run: ./.github/scripts/check-go-mod.sh

      - name: Build Packages
        run: ./.github/scripts/build-packages.sh

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.12.2
          skip-cache: true
