---
name: Verify Changes

on:
  pull_request:
    branches:
      - main

jobs:
  verify-changes:
    name: golang-ci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "./go.mod"

      - name: Go Version
        run: go version

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/

      - name: Verify Go Mod
        run: ./.github/scripts/check-go-mod.sh

      - name: Build Packages
        run: ./.github/scripts/build-packages.sh

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.12.2
          skip-cache: true
