---
name: Run Test Suite
description: "Runs test suite"
inputs:
  package:
    description: "Package to test"
    required: true
  test-suite:
    description: "Suite to test"
    required: true
  timeout:
    description: "Timeout"
    required: true
runs:
  using: composite
  steps:
    - name: Run Tests
      id: tests
      run: |
        set +e
        gotestsum --format standard-verbose --packages=github.com/rancher/tfp-automation/tests/${{ inputs.package }} \
        --junitfile results.xml --jsonfile results.json -- -timeout=${{ inputs.timeout }} -v -run "${{ inputs.test-suite }}"
      shell: bash