package harvester

const (
	Harvester = "harvester"
	CPU       = "cpu"
	Memory    = "memory"

	CloudInit          = "cloudinit"
	UserDataSecretName = "user_data_secret_name"
	NetworkData        = "network_data"

	Disk                    = "disk"
	EFI                     = "efi"
	SecureBoot              = "secure_boot"
	RunStrategy             = "run_strategy"
	Hostname                = "hostname"
	HarvesterSource         = "harvester/harvester"
	SshUser                 = "ssh-user"
	KubernetesSecret        = "kubernetes_secret"
	HarvesterVirtualMachine = "harvester_virtualmachine"
	HarvesterSSHKey         = "harvester_ssh_key"
	RerunOnFailure          = "RerunOnFailure"
	PublicKey               = "public_key"
	Size                    = "size"
	Timeout                 = "timeout"
	BootOrder               = "boot_order"
	Image                   = "image"
	AutoDelete              = "auto_delete"
	Bus                     = "bus"
	Q35                     = "q35"
	MachineType             = "machine_type"
	Ubuntu                  = "ubuntu"
	Gi                      = "Gi"

	Labels           = "labels"
	LowerCaseName    = "name"
	ModulePath       = "module_path"
	ModuleRelPath    = "module_rel_path"
	CodebaseRootPath = "codebase_root_path"

	NetworkName        = "network_name"
	NetworkInterface   = "network_interface"
	NIC1               = "nic-1"
	Model              = "model"
	WaitForLease       = "wait_for_lease"
	Virtio             = "virtio"
	Bridge             = "bridge"
	RestartAfterUpdate = "restart_after_update"
	RootDisk           = "rootdisk"
)
